/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt -i isd.ggo -F isd_cmdline 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "isd_cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: isd [OPTION]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help               Print help and exit",
  "  -V, --version            Print version and exit",
  "  -i, --input=filename     Input file (default : standart input)",
  "  -s, --seed=LONGLONG      Seed of the pseudo random generator",
  "  -I, --max_iter=LONGLONG  Number of iterations to perform before stopping\n                             (default=`0')",
  "  -S, --max_sol=LONGLONG   Number of solutions to find before stopping\n                             (default=`0')",
  "  -T, --max_time=LONGLONG  Number of second to spend before stopping\n                             (default=`0')",
  "  -w, --w=INT              Maximum weight of the word to find (overrides input\n                             file value)",
  "  -l, --l=INT              Height of the window",
  "  -p, --p=INT              Weight of the error in the window",
  "  -t, --threshold=INT      Threshold on the weight of the first word",
  "  -L, --l2=INT             Height of the window in MMT and BJMM algorithms",
  "  -a, --alpha=INT          Inverse proportion of elements of {0, 1}^l2 used to\n                             form the set A in MMT algorithm. The set will be\n                             composed of 2^(l2-alpha)",
  "  -r, --l3=INT             Height of the window",
  "  -e, --e1=INT             Additional error accepted for fusion before filter 1\n                             in BJMM algorithm",
  "  -E, --e2=INT             Additional error accepted for fusion before filter 2\n                             in BJMM algorithm",
  "  -c, --csize=INT          number of 64bit int used to represent a column\n                             during list merging. Choose l <= csize*64 <= r .\n                             min value for minimum spatial complexity, max\n                             value for minimum temporal complexity ",
  "  -k, --skip=INT           Number of iteration to skip before beginning\n                             (default=`0')",
  "  -v, --verbose=INT        verbosity level  (default=`1')",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
  , ARG_LONGLONG
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_given = 0 ;
  args_info->seed_given = 0 ;
  args_info->max_iter_given = 0 ;
  args_info->max_sol_given = 0 ;
  args_info->max_time_given = 0 ;
  args_info->w_given = 0 ;
  args_info->l_given = 0 ;
  args_info->p_given = 0 ;
  args_info->threshold_given = 0 ;
  args_info->l2_given = 0 ;
  args_info->alpha_given = 0 ;
  args_info->l3_given = 0 ;
  args_info->e1_given = 0 ;
  args_info->e2_given = 0 ;
  args_info->csize_given = 0 ;
  args_info->skip_given = 0 ;
  args_info->verbose_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->input_arg = NULL;
  args_info->input_orig = NULL;
  args_info->seed_orig = NULL;
  args_info->max_iter_arg = 0;
  args_info->max_iter_orig = NULL;
  args_info->max_sol_arg = 0;
  args_info->max_sol_orig = NULL;
  args_info->max_time_arg = 0;
  args_info->max_time_orig = NULL;
  args_info->w_orig = NULL;
  args_info->l_orig = NULL;
  args_info->p_orig = NULL;
  args_info->threshold_orig = NULL;
  args_info->l2_orig = NULL;
  args_info->alpha_orig = NULL;
  args_info->l3_orig = NULL;
  args_info->e1_orig = NULL;
  args_info->e2_orig = NULL;
  args_info->csize_orig = NULL;
  args_info->skip_arg = 0;
  args_info->skip_orig = NULL;
  args_info->verbose_arg = 1;
  args_info->verbose_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->input_help = gengetopt_args_info_help[2] ;
  args_info->seed_help = gengetopt_args_info_help[3] ;
  args_info->max_iter_help = gengetopt_args_info_help[4] ;
  args_info->max_sol_help = gengetopt_args_info_help[5] ;
  args_info->max_time_help = gengetopt_args_info_help[6] ;
  args_info->w_help = gengetopt_args_info_help[7] ;
  args_info->l_help = gengetopt_args_info_help[8] ;
  args_info->p_help = gengetopt_args_info_help[9] ;
  args_info->threshold_help = gengetopt_args_info_help[10] ;
  args_info->l2_help = gengetopt_args_info_help[11] ;
  args_info->alpha_help = gengetopt_args_info_help[12] ;
  args_info->l3_help = gengetopt_args_info_help[13] ;
  args_info->e1_help = gengetopt_args_info_help[14] ;
  args_info->e2_help = gengetopt_args_info_help[15] ;
  args_info->csize_help = gengetopt_args_info_help[16] ;
  args_info->skip_help = gengetopt_args_info_help[17] ;
  args_info->verbose_help = gengetopt_args_info_help[18] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->input_arg));
  free_string_field (&(args_info->input_orig));
  free_string_field (&(args_info->seed_orig));
  free_string_field (&(args_info->max_iter_orig));
  free_string_field (&(args_info->max_sol_orig));
  free_string_field (&(args_info->max_time_orig));
  free_string_field (&(args_info->w_orig));
  free_string_field (&(args_info->l_orig));
  free_string_field (&(args_info->p_orig));
  free_string_field (&(args_info->threshold_orig));
  free_string_field (&(args_info->l2_orig));
  free_string_field (&(args_info->alpha_orig));
  free_string_field (&(args_info->l3_orig));
  free_string_field (&(args_info->e1_orig));
  free_string_field (&(args_info->e2_orig));
  free_string_field (&(args_info->csize_orig));
  free_string_field (&(args_info->skip_orig));
  free_string_field (&(args_info->verbose_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->input_given)
    write_into_file(outfile, "input", args_info->input_orig, 0);
  if (args_info->seed_given)
    write_into_file(outfile, "seed", args_info->seed_orig, 0);
  if (args_info->max_iter_given)
    write_into_file(outfile, "max_iter", args_info->max_iter_orig, 0);
  if (args_info->max_sol_given)
    write_into_file(outfile, "max_sol", args_info->max_sol_orig, 0);
  if (args_info->max_time_given)
    write_into_file(outfile, "max_time", args_info->max_time_orig, 0);
  if (args_info->w_given)
    write_into_file(outfile, "w", args_info->w_orig, 0);
  if (args_info->l_given)
    write_into_file(outfile, "l", args_info->l_orig, 0);
  if (args_info->p_given)
    write_into_file(outfile, "p", args_info->p_orig, 0);
  if (args_info->threshold_given)
    write_into_file(outfile, "threshold", args_info->threshold_orig, 0);
  if (args_info->l2_given)
    write_into_file(outfile, "l2", args_info->l2_orig, 0);
  if (args_info->alpha_given)
    write_into_file(outfile, "alpha", args_info->alpha_orig, 0);
  if (args_info->l3_given)
    write_into_file(outfile, "l3", args_info->l3_orig, 0);
  if (args_info->e1_given)
    write_into_file(outfile, "e1", args_info->e1_orig, 0);
  if (args_info->e2_given)
    write_into_file(outfile, "e2", args_info->e2_orig, 0);
  if (args_info->csize_given)
    write_into_file(outfile, "csize", args_info->csize_orig, 0);
  if (args_info->skip_given)
    write_into_file(outfile, "skip", args_info->skip_orig, 0);
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", args_info->verbose_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->l_given)
    {
      fprintf (stderr, "%s: '--l' ('-l') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_LONGLONG:
#if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
    if (val) *((long long int*)field) = (long long int) strtoll (val, &stop_char, 0);
#else
    if (val) *((long *)field) = (long)strtol (val, &stop_char, 0);
#endif
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_LONGLONG:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input",	1, NULL, 'i' },
        { "seed",	1, NULL, 's' },
        { "max_iter",	1, NULL, 'I' },
        { "max_sol",	1, NULL, 'S' },
        { "max_time",	1, NULL, 'T' },
        { "w",	1, NULL, 'w' },
        { "l",	1, NULL, 'l' },
        { "p",	1, NULL, 'p' },
        { "threshold",	1, NULL, 't' },
        { "l2",	1, NULL, 'L' },
        { "alpha",	1, NULL, 'a' },
        { "l3",	1, NULL, 'r' },
        { "e1",	1, NULL, 'e' },
        { "e2",	1, NULL, 'E' },
        { "csize",	1, NULL, 'c' },
        { "skip",	1, NULL, 'k' },
        { "verbose",	1, NULL, 'v' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVi:s:I:S:T:w:l:p:t:L:a:r:e:E:c:k:v:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'i':	/* Input file (default : standart input).  */
        
        
          if (update_arg( (void *)&(args_info->input_arg), 
               &(args_info->input_orig), &(args_info->input_given),
              &(local_args_info.input_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input", 'i',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Seed of the pseudo random generator.  */
        
        
          if (update_arg( (void *)&(args_info->seed_arg), 
               &(args_info->seed_orig), &(args_info->seed_given),
              &(local_args_info.seed_given), optarg, 0, 0, ARG_LONGLONG,
              check_ambiguity, override, 0, 0,
              "seed", 's',
              additional_error))
            goto failure;
        
          break;
        case 'I':	/* Number of iterations to perform before stopping.  */
        
        
          if (update_arg( (void *)&(args_info->max_iter_arg), 
               &(args_info->max_iter_orig), &(args_info->max_iter_given),
              &(local_args_info.max_iter_given), optarg, 0, "0", ARG_LONGLONG,
              check_ambiguity, override, 0, 0,
              "max_iter", 'I',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* Number of solutions to find before stopping.  */
        
        
          if (update_arg( (void *)&(args_info->max_sol_arg), 
               &(args_info->max_sol_orig), &(args_info->max_sol_given),
              &(local_args_info.max_sol_given), optarg, 0, "0", ARG_LONGLONG,
              check_ambiguity, override, 0, 0,
              "max_sol", 'S',
              additional_error))
            goto failure;
        
          break;
        case 'T':	/* Number of second to spend before stopping.  */
        
        
          if (update_arg( (void *)&(args_info->max_time_arg), 
               &(args_info->max_time_orig), &(args_info->max_time_given),
              &(local_args_info.max_time_given), optarg, 0, "0", ARG_LONGLONG,
              check_ambiguity, override, 0, 0,
              "max_time", 'T',
              additional_error))
            goto failure;
        
          break;
        case 'w':	/* Maximum weight of the word to find (overrides input file value).  */
        
        
          if (update_arg( (void *)&(args_info->w_arg), 
               &(args_info->w_orig), &(args_info->w_given),
              &(local_args_info.w_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "w", 'w',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* Height of the window.  */
        
        
          if (update_arg( (void *)&(args_info->l_arg), 
               &(args_info->l_orig), &(args_info->l_given),
              &(local_args_info.l_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "l", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Weight of the error in the window.  */
        
        
          if (update_arg( (void *)&(args_info->p_arg), 
               &(args_info->p_orig), &(args_info->p_given),
              &(local_args_info.p_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "p", 'p',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Threshold on the weight of the first word.  */
        
        
          if (update_arg( (void *)&(args_info->threshold_arg), 
               &(args_info->threshold_orig), &(args_info->threshold_given),
              &(local_args_info.threshold_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "threshold", 't',
              additional_error))
            goto failure;
        
          break;
        case 'L':	/* Height of the window in MMT and BJMM algorithms.  */
        
        
          if (update_arg( (void *)&(args_info->l2_arg), 
               &(args_info->l2_orig), &(args_info->l2_given),
              &(local_args_info.l2_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "l2", 'L',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Inverse proportion of elements of {0, 1}^l2 used to form the set A in MMT algorithm. The set will be composed of 2^(l2-alpha).  */
        
        
          if (update_arg( (void *)&(args_info->alpha_arg), 
               &(args_info->alpha_orig), &(args_info->alpha_given),
              &(local_args_info.alpha_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "alpha", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* Height of the window.  */
        
        
          if (update_arg( (void *)&(args_info->l3_arg), 
               &(args_info->l3_orig), &(args_info->l3_given),
              &(local_args_info.l3_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "l3", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'e':	/* Additional error accepted for fusion before filter 1 in BJMM algorithm.  */
        
        
          if (update_arg( (void *)&(args_info->e1_arg), 
               &(args_info->e1_orig), &(args_info->e1_given),
              &(local_args_info.e1_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "e1", 'e',
              additional_error))
            goto failure;
        
          break;
        case 'E':	/* Additional error accepted for fusion before filter 2 in BJMM algorithm.  */
        
        
          if (update_arg( (void *)&(args_info->e2_arg), 
               &(args_info->e2_orig), &(args_info->e2_given),
              &(local_args_info.e2_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "e2", 'E',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* number of 64bit int used to represent a column during list merging. Choose l <= csize*64 <= r . min value for minimum spatial complexity, max value for minimum temporal complexity .  */
        
        
          if (update_arg( (void *)&(args_info->csize_arg), 
               &(args_info->csize_orig), &(args_info->csize_given),
              &(local_args_info.csize_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "csize", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'k':	/* Number of iteration to skip before beginning.  */
        
        
          if (update_arg( (void *)&(args_info->skip_arg), 
               &(args_info->skip_orig), &(args_info->skip_given),
              &(local_args_info.skip_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "skip", 'k',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* verbosity level.  */
        
        
          if (update_arg( (void *)&(args_info->verbose_arg), 
               &(args_info->verbose_orig), &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "verbose", 'v',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
